# Generated by Django 5.0.2 on 2024-02-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('code_qpv', models.CharField(max_length=255)),
                ('nom_qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('federation', models.CharField(max_length=255)),
                ('clubs', models.CharField(max_length=255)),
                ('epa', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
