# Generated by Django 5.0.2 on 2024-02-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ods',
            name='total',
        ),
    ]
