# Generated by Django 5.0.2 on 2024-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ods_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('code_QPV', models.CharField(max_length=255)),
                ('name_qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('fede', models.CharField(max_length=255)),
                ('f1_4', models.IntegerField()),
                ('f5_9', models.IntegerField()),
                ('f10_14', models.IntegerField()),
                ('f15_19', models.IntegerField()),
                ('f20_24', models.IntegerField()),
                ('f25_29', models.IntegerField()),
                ('f30_34', models.IntegerField()),
                ('f35_39', models.IntegerField()),
                ('f40_44', models.IntegerField()),
                ('f45_49', models.IntegerField()),
                ('f50_54', models.IntegerField()),
                ('f55_59', models.IntegerField()),
                ('f60_64', models.IntegerField()),
                ('f64_69', models.IntegerField()),
                ('f70_74', models.IntegerField()),
                ('f75_79', models.IntegerField()),
                ('f80_99', models.IntegerField()),
                ('f_nr', models.IntegerField()),
                ('h1_4', models.IntegerField()),
                ('h5_9', models.IntegerField()),
                ('h10_14', models.IntegerField()),
                ('h15_19', models.IntegerField()),
                ('h20_24', models.IntegerField()),
                ('h25_29', models.IntegerField()),
                ('h30_34', models.IntegerField()),
                ('h35_39', models.IntegerField()),
                ('h40_44', models.IntegerField()),
                ('h45_49', models.IntegerField()),
                ('h50_54', models.IntegerField()),
                ('h55_59', models.IntegerField()),
                ('h60_64', models.IntegerField()),
                ('h64_69', models.IntegerField()),
                ('h70_74', models.IntegerField()),
                ('h75_79', models.IntegerField()),
                ('h80_99', models.IntegerField()),
                ('h_nr', models.IntegerField()),
                ('NRNR', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
