# Generated by Django 5.0.2 on 2024-02-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ods_license_nrnr_alter_ods_license_f10_14_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='d_age',
            fields=[
                ('code_age', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='d_club_type',
            fields=[
                ('code_club_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='d_date',
            fields=[
                ('date_PK', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='d_federation',
            fields=[
                ('code_federation', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='d_geo',
            fields=[
                ('code_commune', models.IntegerField(default=None)),
                ('label_commune', models.CharField(max_length=150)),
                ('code_qpv', models.IntegerField(default=None)),
                ('label_qpv', models.CharField(max_length=150)),
                ('code_departement', models.IntegerField(default=None)),
                ('label_departement', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('statut_geo', models.CharField(default=None, max_length=150)),
                ('geo_key', models.CharField(default=None, max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='d_sex',
            fields=[
                ('code_sex', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='f_club',
            fields=[
                ('count', models.IntegerField(default=None)),
                ('club_PK', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('club_type_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_club_type')),
                ('date_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('federation_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('geo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geo')),
            ],
        ),
        migrations.CreateModel(
            name='f_license',
            fields=[
                ('count', models.IntegerField(default=None)),
                ('license_PK', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('age_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_age')),
                ('date_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('federation_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('geo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geo')),
                ('sex_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_sex')),
            ],
        ),
    ]
