# Generated by Django 5.0.2 on 2024-02-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_d_age_d_club_type_d_date_d_federation_d_geo_d_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_geo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f_club',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f_license',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='d_geo',
            name='geo_key',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='f_club',
            name='club_PK',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='f_license',
            name='license_PK',
            field=models.CharField(max_length=250),
        ),
    ]
