# Generated by Django 5.0.2 on 2024-02-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_d_geo_id_f_club_id_f_license_id_alter_d_geo_geo_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_geo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='f_club',
            name='id',
        ),
        migrations.RemoveField(
            model_name='f_license',
            name='id',
        ),
        migrations.AlterField(
            model_name='d_geo',
            name='geo_key',
            field=models.CharField(default=None, max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='f_club',
            name='club_PK',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='f_license',
            name='license_PK',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
