# Generated by Django 5.0.2 on 2024-02-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_d_geo_id_remove_f_club_id_remove_f_license_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_geo',
            name='code_commune',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='d_geo',
            name='code_qpv',
            field=models.CharField(max_length=150),
        ),
    ]
