# Generated by Django 5.0.2 on 2024-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_d_geo_code_commune_alter_d_geo_code_qpv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_age',
            name='code_age',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_club_type',
            name='code_club_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_date',
            name='date_PK',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_federation',
            name='code_federation',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_geo',
            name='geo_key',
            field=models.CharField(default=None, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_sex',
            name='code_sex',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='f_club',
            name='club_PK',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='f_license',
            name='license_PK',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
