# Generated by Django 5.0.2 on 2024-02-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_d_age_code_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_date',
            name='date_PK',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='d_geo',
            name='code_departement',
            field=models.CharField(max_length=150),
        ),
    ]
