# Generated by Django 5.0.2 on 2024-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_d_date_date_pk_alter_d_geo_code_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_date',
            name='date_PK',
            field=models.DateField(primary_key=True, serialize=False, unique=True),
        ),
    ]
