# Generated by Django 5.0.2 on 2024-02-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_license',
            name='date_FK',
        ),
    ]
